"""PDF Generator for Quantity Barcodes."""
import io
import barcode
from barcode.writer import ImageWriter
from reportlab.lib.pagesizes import A4
from reportlab.lib.units import mm
from reportlab.pdfgen import canvas
from PIL import Image


def generate_quantity_barcodes_pdf():
    """Generate a PDF with quantity barcodes (1-9, 10, 20, 30)."""
    # Create PDF buffer
    buffer = io.BytesIO()

    # Create canvas (A4 size)
    c = canvas.Canvas(buffer, pagesize=A4)
    width, height = A4

    # Title
    c.setFont("Helvetica-Bold", 20)
    c.drawString(50, height - 50, "Barcode Buddy - Quantity Barcodes")

    c.setFont("Helvetica", 12)
    c.drawString(50, height - 70, "Scan these barcodes to set quantity before scanning products")

    # Define quantities to generate
    quantities = [1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 20, 30]

    # Layout settings
    start_y = height - 120
    barcode_height = 60
    spacing = 80
    left_margin = 50
    right_column_x = width / 2 + 20

    # Generate barcodes
    for idx, qty in enumerate(quantities):
        barcode_text = f"BBUDDY-Q-{qty}"

        # Determine position (2 columns)
        col = idx % 2
        row = idx // 2

        x_pos = left_margin if col == 0 else right_column_x
        y_pos = start_y - (row * spacing)

        # Generate barcode image
        try:
            # Create Code128 barcode
            code128 = barcode.get_barcode_class('code128')
            barcode_img = code128(barcode_text, writer=ImageWriter())

            # Save to buffer
            img_buffer = io.BytesIO()
            barcode_img.write(img_buffer, options={
                'module_height': 10,
                'module_width': 0.3,
                'font_size': 10,
                'text_distance': 3,
                'quiet_zone': 2
            })
            img_buffer.seek(0)

            # Draw barcode on PDF
            c.drawImage(img_buffer, x_pos, y_pos - barcode_height,
                       width=180, height=barcode_height, preserveAspectRatio=True)

            # Add label above barcode
            c.setFont("Helvetica-Bold", 14)
            c.drawString(x_pos, y_pos + 5, f"Quantity: {qty}")

        except Exception as e:
            # Fallback: just draw text if barcode generation fails
            c.setFont("Helvetica", 10)
            c.drawString(x_pos, y_pos, f"Error generating barcode: {barcode_text}")

    # Footer
    c.setFont("Helvetica-Oblique", 10)
    c.drawString(50, 30, "Generated by Barcode Buddy (Python)")

    # Save PDF
    c.save()

    # Return buffer
    buffer.seek(0)
    return buffer
