"""PDF Generator for Quantity Barcodes."""
import io
from reportlab.lib.pagesizes import A4
from reportlab.lib.units import mm
from reportlab.pdfgen import canvas
from reportlab.graphics.barcode import code128
from reportlab.graphics import renderPDF
from reportlab.graphics.shapes import Drawing


def generate_quantity_barcodes_pdf():
    """Generate a PDF with quantity barcodes (1-9, 10, 20, 30)."""
    # Create PDF buffer
    buffer = io.BytesIO()

    # Create canvas (A4 size)
    c = canvas.Canvas(buffer, pagesize=A4)
    width, height = A4

    # Title
    c.setFont("Helvetica-Bold", 20)
    c.drawString(50, height - 50, "Barcode Buddy - Control Barcodes")

    c.setFont("Helvetica", 12)
    c.drawString(50, height - 70, "Scan these barcodes to control Barcode Buddy")

    # Layout settings
    left_margin = 50
    right_column_x = width / 2 + 20
    barcode_height = 50

    # Section 1: Mode Barcodes (ADD/CONSUME)
    c.setFont("Helvetica-Bold", 16)
    c.drawString(50, height - 110, "Mode Control:")

    mode_y = height - 140

    # ADD mode barcode
    try:
        c.setFont("Helvetica-Bold", 14)
        c.drawString(left_margin, mode_y + 10, "➕ ADD Mode")

        barcode_obj = code128.Code128(
            "BBUDDY-ADD",
            barWidth=1.2,
            barHeight=barcode_height,
            humanReadable=True,
            fontSize=10
        )
        barcode_obj.drawOn(c, left_margin, mode_y - barcode_height - 5)
    except Exception as e:
        c.setFont("Helvetica", 8)
        c.drawString(left_margin, mode_y, f"Error: {str(e)[:50]}")

    # CONSUME mode barcode
    try:
        c.setFont("Helvetica-Bold", 14)
        c.drawString(right_column_x, mode_y + 10, "➖ CONSUME Mode")

        barcode_obj = code128.Code128(
            "BBUDDY-CONSUME",
            barWidth=1.2,
            barHeight=barcode_height,
            humanReadable=True,
            fontSize=10
        )
        barcode_obj.drawOn(c, right_column_x, mode_y - barcode_height - 5)
    except Exception as e:
        c.setFont("Helvetica", 8)
        c.drawString(right_column_x, mode_y, f"Error: {str(e)[:50]}")

    # Section 2: Quantity Barcodes
    c.setFont("Helvetica-Bold", 16)
    c.drawString(50, mode_y - 100, "Quantity Control:")

    # Define quantities to generate
    quantities = [3, 4, 5, 6, 7, 8, 9, 10, 20, 30]

    # Layout settings for quantities
    start_y = mode_y - 130
    spacing = 90

    # Generate barcodes
    for idx, qty in enumerate(quantities):
        barcode_text = f"BBUDDY-Q-{qty}"

        # Determine position (2 columns)
        col = idx % 2
        row = idx // 2

        x_pos = left_margin if col == 0 else right_column_x
        y_pos = start_y - (row * spacing)

        try:
            # Add label above barcode
            c.setFont("Helvetica-Bold", 14)
            c.drawString(x_pos, y_pos + 10, f"Quantity: {qty}")

            # Create Code128 barcode using reportlab
            barcode_obj = code128.Code128(
                barcode_text,
                barWidth=1.2,
                barHeight=barcode_height,
                humanReadable=True,
                fontSize=10
            )

            # Draw barcode
            barcode_obj.drawOn(c, x_pos, y_pos - barcode_height - 5)

        except Exception as e:
            # Fallback: just draw text if barcode generation fails
            c.setFont("Helvetica", 10)
            c.drawString(x_pos, y_pos, f"Error: {barcode_text}")
            c.setFont("Helvetica", 8)
            c.drawString(x_pos, y_pos - 15, f"{str(e)[:50]}")

    # Footer
    c.setFont("Helvetica-Oblique", 10)
    c.drawString(50, 30, "Generated by Barcode Buddy (Python)")

    # Save PDF
    c.save()

    # Return buffer
    buffer.seek(0)
    return buffer
